name = "Modpack 2"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbf4f91a64c8309a42d5db2010684c9b0a2e989465e5ebf7c17d4c4fe57813f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
