name = "Modpack 2"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22f559dc644c7ec1984d360f49c885d842d7dfa420db157eb2e75a442023dab9"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
