name = "Modpack 2"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d10db87d8ef71739913d2d0e0663eee4fbb0475e12122aaf97d88931eda5aece"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
