name = "Modpack 2"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "275358de844cff43b58d583721b90a0e7f5aec686c4e5ea5f48e2389fc426c0b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
