name = "Modpack 2"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f65cb2039ecd2e329f67d04a7805f0a3f0a4cac01824d00484d67b2b4b2d2f93"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
