name = "Modpack 2"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f68f402693d921e0fe3f688a77b9855c14a34b10a96b087a9e100b1d47b8e720"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
